config/routes.rb
Rails.application.routes.draw do
  root 'dogs#index'
  resources :dogs

end

app/models/dog.rb
class Dog < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
    @dogs = Dog.all
  end

  def new
    @dog = Dog.new
  end

  def create
    @dog = Dog.create(dog_params)
    redirect_to root_path
  end

  private

  def dog_params
    params.require(:dog).permit(:breed, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/index.html.erb
<h1>Dogs are the best pets!</h1>

<%= button_to 'Add a Dog!', new_dog_path, method: :get %>

<% @dogs.each do |dog| %>
  <h3><strong><%= dog.breed %></strong></h3>
  <p><%= dog.description %></p>
  <br/>
<% end %>

app/views/dogs/new.html.erb
<h1>Add a Dog!</h1>

<%= simple_form_for @dog do |f| %>
  <%= f.input :breed %>
  <br/>
  <%= f.input :description %>
  <br/>
  <%= f.submit 'Add Your Dog' %>
<% end %>

<br/>
<%= button_to 'See All Dogs', root_path, method: :get %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dog Breed Info</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>